<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AirMirror</AssemblyName>
    <RootNamespace>AirMirror</RootNamespace>
    <ApplicationIcon Condition="Exists('..\\assets\\AirMirror.ico')">..\assets\AirMirror.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
