<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AirMirror</AssemblyName>
    <RootNamespace>AirMirror</RootNamespace>
    <ApplicationIcon Condition="Exists('..\\..\\构建\\临时\\品牌素材\\AirMirror.ico')">..\..\构建\临时\品牌素材\AirMirror.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>
</Project>
